name: My Workflow

on: [push] # Event that triggers the workflow

jobs:
  build: # A job named 'build'
    runs-on: ubuntu-latest # Runner environment

    steps:
      - uses: actions/checkout@v4 # Action to checkout the repository code
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
